# Generated by Django 4.2.6 on 2023-10-13 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30)),
                ('nom_de_famille', models.CharField(max_length=40)),
                ('date_de_naissance', models.DateField()),
                ('a_un_animal_de_compagnie', models.BooleanField(default=True)),
                ('nombre_d_animaux_de_compagnie', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('categorie', models.CharField(max_length=50)),
                ('date_de_publication', models.DateField(default=datetime.datetime(2023, 10, 13, 5, 6, 18, 343510))),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
            ],
        ),
    ]
