# Generated by Django 4.2.6 on 2023-10-13 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_person_nombre_d_animaux_de_compagnie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_de_publication',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 17, 54, 12, 660728)),
        ),
    ]
