# Generated by Django 4.2.6 on 2023-10-14 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_post_date_de_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('J', 'Journal'), ('T', 'Technologie'), ('P', 'Politique'), ('E', 'Economique')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_de_publication',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 23, 30, 22, 173261)),
        ),
    ]
